from common.errors.errors import (
    BodyMakeErrors,
    DashboardErrors,
    MealErrors,
    ProfileErrors,
    WaterErrors,
    WorkoutErrors,
)

VALIDATION_ERROR_MAP = {
    ("GET", "/dashboard/daily-summary", "date"): DashboardErrors.INVALID_DATE,
    ("GET", "/dashboard/monthly-markers", "month"): DashboardErrors.INVALID_DATE,
    ("GET", "/meal-logs", "date"): MealErrors.INVALID_DATE,
    ("GET", "/workout-logs", "date"): WorkoutErrors.INVALID_DATE,
    ("GET", "/water-logs", "date"): WaterErrors.INVALID_DATE,
    ("PUT", "/profile", "height"): ProfileErrors.INVALID_HEIGHT,
    ("PUT", "/profile", "weight"): ProfileErrors.INVALID_WEIGHT,
    ("PUT", "/profile", "age"): ProfileErrors.INVALID_AGE,
    ("PUT", "/profile", "gender"): ProfileErrors.INVALID_GENDER,
    ("PUT", "/profile", "activity_level"): ProfileErrors.INVALID_ACTIVITY_LEVEL,
    ("PUT", "/profile", "daily_water_goal_ml"): ProfileErrors.INVALID_DAILY_WATER_GOAL,
    ("PUT", "/body-make-plans", "course"): BodyMakeErrors.INVALID_GOAL_COURSE,
    ("PUT", "/body-make-plans", "effective_from"): BodyMakeErrors.INVALID_EFFECTIVE_FROM,
    ("PUT", "/body-make-plans", "target_weight_kg"): BodyMakeErrors.INVALID_TARGET_WEIGHT_KG,
    ("PUT", "/body-make-plans", "duration_days"): BodyMakeErrors.INVALID_DURATION_DAYS,
    ("POST", "/meal-logs", "meal_name"): MealErrors.INVALID_MEAL_NAME,
    ("POST", "/meal-logs", "calories"): MealErrors.INVALID_CALORIES,
    ("POST", "/meal-logs", "eaten_at"): MealErrors.INVALID_EATEN_AT,
    ("PUT", "/meal-logs/{meal_id}", "meal_id"): MealErrors.INVALID_ID_FOR_UPDATE,
    ("PUT", "/meal-logs/{meal_id}", "meal_name"): MealErrors.INVALID_MEAL_NAME_FOR_UPDATE,
    ("PUT", "/meal-logs/{meal_id}", "calories"): MealErrors.INVALID_CALORIES_FOR_UPDATE,
    ("PUT", "/meal-logs/{meal_id}", "eaten_at"): MealErrors.INVALID_EATEN_AT_FOR_UPDATE,
    ("DELETE", "/meal-logs/{meal_id}", "meal_id"): MealErrors.INVALID_ID_FOR_DELETE,
    ("POST", "/workout-logs", "workout_name"): WorkoutErrors.INVALID_WORKOUT_NAME,
    ("POST", "/workout-logs", "burned_calories"): WorkoutErrors.INVALID_BURNED_CALORIES,
    ("POST", "/workout-logs", "worked_out_at"): WorkoutErrors.INVALID_WORKED_OUT_AT,
    ("PUT", "/workout-logs/{workout_id}", "workout_id"): WorkoutErrors.INVALID_ID_FOR_UPDATE,
    ("PUT", "/workout-logs/{workout_id}", "workout_name"): WorkoutErrors.INVALID_WORKOUT_NAME_FOR_UPDATE,
    ("PUT", "/workout-logs/{workout_id}", "burned_calories"): WorkoutErrors.INVALID_BURNED_CALORIES_FOR_UPDATE,
    ("PUT", "/workout-logs/{workout_id}", "worked_out_at"): WorkoutErrors.INVALID_WORKED_OUT_AT_FOR_UPDATE,
    ("DELETE", "/workout-logs/{workout_id}", "workout_id"): WorkoutErrors.INVALID_ID_FOR_DELETE,
    ("POST", "/water-logs", "amount_ml"): WaterErrors.INVALID_AMOUNT_ML,
    ("POST", "/water-logs", "drank_at"): WaterErrors.INVALID_DRANK_AT,
    ("PUT", "/water-logs/{water_log_id}", "water_log_id"): WaterErrors.INVALID_ID_FOR_UPDATE,
    ("PUT", "/water-logs/{water_log_id}", "amount_ml"): WaterErrors.INVALID_AMOUNT_ML_FOR_UPDATE,
    ("PUT", "/water-logs/{water_log_id}", "drank_at"): WaterErrors.INVALID_DRANK_AT_FOR_UPDATE,
    ("DELETE", "/water-logs/{water_log_id}", "water_log_id"): WaterErrors.INVALID_ID_FOR_DELETE,
}
